debug: false

server:
  port: 9988

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/develop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

input:
  cat:
    server-port: 9990
